// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_tw1Z2V2vGUWzwCEV-Xlpr4RZQ-n8-7Q',
    appId: '1:284203501080:web:775eb2e659bc278f67656d',
    messagingSenderId: '284203501080',
    projectId: 'fmct-6151b',
    authDomain: 'fmct-6151b.firebaseapp.com',
    storageBucket: 'fmct-6151b.appspot.com',
    measurementId: 'G-K15EQYWEMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw0rNAG1rbjdPF8lgDu0KYss1gavAi0s0',
    appId: '1:284203501080:android:490873ce78ea915367656d',
    messagingSenderId: '284203501080',
    projectId: 'fmct-6151b',
    storageBucket: 'fmct-6151b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQAdum1jpQoOcUYOMneQdWSTnQ2sjPxWk',
    appId: '1:284203501080:ios:4a0e3689b8f5724e67656d',
    messagingSenderId: '284203501080',
    projectId: 'fmct-6151b',
    storageBucket: 'fmct-6151b.appspot.com',
    iosClientId: '284203501080-lkp2p8rc1r9abud5rvgto8fkhqrul93l.apps.googleusercontent.com',
    iosBundleId: 'com.example.mazzad',
  );
}
